# Generated by Django 5.1.4 on 2026-05-30 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stories", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25, unique=True)),
                ("slug", models.CharField(max_length=25, unique=True)),
            ],
            options={
                "db_table": "genres",
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25, unique=True)),
                ("slug", models.CharField(max_length=25, unique=True)),
            ],
            options={
                "db_table": "tags",
            },
        ),
        migrations.AddField(
            model_name="story",
            name="genre",
            field=models.ManyToManyField(blank=True, to="stories.genre"),
        ),
        migrations.AddField(
            model_name="story",
            name="tags",
            field=models.ManyToManyField(blank=True, to="stories.tag"),
        ),
    ]
